### ISSUE TITLE
Website Logo > Right clicking on Remix logo takes user to google drive with Remix logo image files in it

### ISSUE THREAD

**Issue by dendrobiummoniliforme** [remix-run/remix-website#198]
### Reproduction

1. Visit https://remix.run/
2. Right click on the Remix Logo (Top Left).
3. Observe redirect to https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c

### System Info

```shell
Reproduced on Firefox (119.0.1 (64-bit)) and Safari (Version 16.3 (18614.4.6.1.6)).
macOS 13.2.1 (22D68)
```

### Expected Behavior

OS / Web. Browser Specific context menu appears.

### Actual Behavior

User redirected to google drive folder containing logos.

I'll note that if this is expected, that is fine. Have not seen this before, but I could understand a use-case such as:
1. I want to download the image.
2. Redirect user to a folder with all original images.

**Comment by dendrobiummoniliforme** [comment]
Gathering info:
* Looks like this was introduced in https://github.com/remix-run/remix-website/pull/73

Which seemed to want to bring the pages more inline with React Router https://reactrouter.com/en/main which when a user right clicks on the React Router website logo they do get directed to https://reactrouter.com/brand which is a webpage dedicated to assets. It is not a google drive but my original thought about its usage seems correct.

I guess the questions are: 
* Should this instead link to a brand route much like the React Router page?
* Does it matter?

**Comment by brookslybrand** [comment]
Hi @dendrobiummoniliforme, thanks for bringing this up. This is in fact expected behavior. I'm not sure where we took this from, but I've seen it done on many websites. Here is Astro for example:

https://github.com/remix-run/remix-website/assets/12396812/1b6cb21d-5cab-4fd2-aa60-cc89198bda5e

While I agree we can probably give a slightly better experience than ripping you our site's context and into Google Drive, we do prefer to send you to all of the official, high quality assets if you're attempting to copy the logo.

So to your question

> Should this instead link to a brand route much like the React Router page?

I think that could be cool! If this is something you're interested in taking on feel free to explore it, otherwise I can open a new issue with a more direct ask/mockup.

**Comment by brookslybrand** [comment]
I posted that and then just realized that you've already opened up #199 😅 

Thanks for doing that 🤘 I'll take a look today or tomorrow and provide any feedback

**Comment by dendrobiummoniliforme** [comment]
@brookslybrand I think this is good to close :) as per #199

**Comment by brookslybrand** [comment]
Yep! Thanks for bringing this up and all your help @dendrobiummoniliforme :) The team is excited to have this page
