### ISSUE TITLE
Redirect to main branch when only lang slug is present

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/remix-website#98]
From user Alem Tuzlak on Discord:

> Just a small suggestion for the remix docs, it would be cool if i went to remix.run/docs/en it would redirect me to the latest version or the main one of the docs instead of me hitting an error boundary. if you go to remix.run/docs it goes to => remix.run/docs/en/main but if you go to remix.run/docs/en it enters an error boundary

https://discord.com/channels/770287896669978684/770287896669978687/1110137964090101760

**Expected Behavior:**
https://remix.run/en -> redirects to https://remix.run/en/main

**Comment by utkarshpant** [comment]
Hi folks! I'd love to pick this one up, now that I've had a bunch of fun poking around in the repo!

I tried a few ideas but this issue seems a little thorny to me (sorry!). Here's what I tried:
1. Adding a route file matching `docs.$lang.tsx`, and simply redirecting to `docs/:lang/main`. I realised quickly this doesn't work because the `docs/:lang` loader also runs when `docs/:lang/:ref` is hit, causing infinite an redirection loop.
2. The less ideal path was an `_redirects.txt` entry for `docs/en/` to `docs/en/main`, but this fails for other lang codes.

Sorry if I'm missing something obvious [and eating into time], but how would one resolve this? 😄

**Comment by kiliman** [comment]
@utkarshpant In your `docs.$lang.tsx` route, you can check params to see if there is a `ref` param and only redirect if missing.
```ts
import { redirect, type LoaderFunctionArgs } from "@remix-run/node";

export async function loader({ request, params }: LoaderFunctionArgs) {
  return !params.ref ? redirect(`${request.url}/main`) : null;
}
```

**Comment by utkarshpant** [comment]
Thanks, @kiliman, that worked! I've raised a PR for this (#167).

TIL that when `docs/:lang` and `docs/:lang/:ref` both match, the `ref` param is passed to both routes where the loaders will run.

**Comment by brophdawg11** [comment]
FWIW - another way to solve this is via a `docs.$lang._index.tsx` route doing the redirect which eliminates the need to check for a `ref` since it will only match when there isn't a `ref`.  Either solution works great though!

**Comment by brookslybrand** [comment]
> FWIW - another way to solve this is via a `docs.$lang._index.tsx` route doing the redirect which eliminates the need to check for a `ref` since it will only match when there isn't a `ref`. Either solution works great though!

Ah yeah, that would have a been a good approach too. Thanks for adding that

**Comment by kiliman** [comment]
@brophdawg11 That's probably a better solution. This extra route just means we're going to have an additional (useless) loader request. I was so busy replying with a fix to the _infinite_ redirects, that I didn't even see the obvious fix.
